# IMPLIMNETING GRADIENT DECSENT 

In [3]:
import pandas as pd
import numpy as np

In [5]:
data=pd.read_csv('insurance_data.csv')
data.head(5)

age  affordibility  bought_insurance
0   22              1                 0
1   25              0                 0
2   47              1                 1
3   52              0                 0
4   46              1                 1

In [7]:
data.columns

Index(['age', 'affordibility', 'bought_insurance'], dtype='object')

In [9]:
data.shape

(28, 3)

In [11]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test=train_test_split(data.drop(columns="bought_insurance"),data.bought_insurance,test_size=0.25,random_state=25)

In [12]:
X_train.shape

(21, 2)

In [13]:
X_train.columns

Index(['age', 'affordibility'], dtype='object')

In [17]:
X_train.age = X_train.age/100
X_test.age = X_test.age/100

In [19]:
X_train.shape

(21, 2)

In [23]:
y_train.shape

(21,)

In [10]:
import warnings 
warnings.filterwarnings(action="ignore")

In [11]:
import tensorflow as tf
from tensorflow import keras

In [ ]:
model = keras.Sequential([
    #keras.layers.Dense(20,input_shape = (2,), activation="relu"),
    #keras.layers.Dense(10,activation='sigmoid', kernel_initializer='ones', bias_initializer='zeros'),
    keras.layers.Dense(1,input_shape=(2,),activation='sigmoid', kernel_initializer='ones', bias_initializer='zeros')
])
model.compile(optimizer='adam',
              loss='binary_crossentropy',
              metrics=['accuracy'])
model.fit(X_train, y_train, epochs=5000)

Epoch 1/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 1s/step - accuracy: 0.5238 - loss: 0.6748
Epoch 2/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 67ms/step - accuracy: 0.5238 - loss: 0.6745
Epoch 3/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step - accuracy: 0.5238 - loss: 0.6742
Epoch 4/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - accuracy: 0.5238 - loss: 0.6739
Epoch 5/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 82ms/step - accuracy: 0.5238 - loss: 0.6735
Epoch 6/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 80ms/step - accuracy: 0.5238 - loss: 0.6732
Epoch 7/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - accuracy: 0.5238 - loss: 0.6729
Epoch 8/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - accuracy: 0.5238 - loss: 0.6726
Epoch 9/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - accuracy: 0.5238 - loss: 0.6723
Epoch 10/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 60ms/step - accuracy: 0.5238 - loss: 0.6720
Epoch 11/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 80ms/step - accuracy: 0.5238 - loss: 0.6717
Epoch 12/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step - accuracy: 0

In [26]:
model.evaluate(X_test,y_test)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - accuracy: 0.8571 - loss: 0.3892


[0.38924217224121094, 0.8571428656578064]

In [29]:
wights , bias = model.get_weights()
wights , bias

(array([[5.1021643],
        [1.5982637]], dtype=float32),
 array([-2.958813], dtype=float32))

In [31]:
bias

array([-2.958813], dtype=float32)