In [2]:
import numpy as np

In [14]:
Financial_year=np.array(['2018','2019','2020'])
industries_dollar=np.array([[200,220,250],[68,79,105],[110,140,180],[80,85,90]])
industries_dollar

array([[200, 220, 250],
       [ 68,  79, 105],
       [110, 140, 180],
       [ 80,  85,  90]])

In [18]:
industries_rupies=industries_dollar*75
industries_rupies

array([[15000, 16500, 18750],
       [ 5100,  5925,  7875],
       [ 8250, 10500, 13500],
       [ 6000,  6375,  6750]])

In [82]:
total_revenue=np.sum(industries_rupies,axis=0)

In [88]:
total_revenue

array([34350, 39300, 46875])

In [36]:
import pandas as pd

In [48]:
industry_names=['RI','info','TCS','wipro']

In [62]:
table=pd.DataFrame(industries_rupies,index=industry_names,columns=Financial_year)
table

2018   2019   2020
RI     15000  16500  18750
info    5100   5925   7875
TCS     8250  10500  13500
wipro   6000   6375   6750

In [116]:
table.loc["TOTAL"] = total_revenue

In [118]:
table

2018   2019   2020
RI     15000  16500  18750
info    5100   5925   7875
TCS     8250  10500  13500
wipro   6000   6375   6750
TOTAL  34350  39300  46875

In [128]:
# unit_sold
months=['jan','feb','march']
flowers=['Rose','Lotus','Sunflower']
price=np.array([[50,60,25],[10,13,5],[40,70,52]])

In [130]:
unit_sold=pd.DataFrame(price,index=flowers,columns=months)
unit_sold

jan  feb  march
Rose        50   60     25
Lotus       10   13      5
Sunflower   40   70     52

In [126]:
# price per unit 
flowers=['Rose','Lotus','Sunflower']
prices=np.array([20,30,25])
price_per_unit_table=pd.DataFrame(prices,index=flowers)
price_per_unit_table

0
Rose       20
Lotus      30
Sunflower  25

In [134]:
#  totals per month
Total= price*prices
Total

array([[1000, 1800,  625],
       [ 200,  390,  125],
       [ 800, 2100, 1300]])

In [138]:
Totals=np.sum(Total,axis=0)
Totals

array([2000, 4290, 2050])

In [142]:
unit_sold.loc["Totals"]=Totals
unit_sold

jan   feb  march
Rose         50    60     25
Lotus        10    13      5
Sunflower    40    70     52
Totals     2000  4290   2050